### ISSUE TITLE
Cannot horizontal center ngx-chart

### ISSUE THREAD

**Issue by mholleville** [swimlane/ngx-charts#1227]
Hi I can't center my chart ! Can you explain me ?

Is it a bug ?

```html
<div class="container" style="text-align: center; margin: auto;">
        <ngx-charts-line-chart

                align="center"
                [view]="view"
                [scheme]="colorScheme"
                [results]="multi"
                [gradient]="gradient"
                [xAxis]="showXAxis"
                [yAxis]="showYAxis"
                [legend]="showLegend"
                [showXAxisLabel]="showXAxisLabel"
                [showYAxisLabel]="showYAxisLabel"
                [xAxisLabel]="xAxisLabel"
                [yAxisLabel]="yAxisLabel"
                [autoScale]="autoScale"
                [timeline]="timeline"
                (select)="onSelect($event)">
        </ngx-charts-line-chart>
    </div>

**Comment by KingDarBoja** [comment]
Hello @mholleville ,

In order to help you, we need a stackblitz demo to check what's going on. 

As I can see, you are trying to center the chart by using some css inline styles. I don't think that's what you have to do, I would recommend wrapping the chart inside another div which handles the positioning  like this:

```html
<div class="chart-container">
    <div class="spectre-line-chart">
        <ngx-charts-line-chart [scheme]="config.colors" [results]="config.data"
            [roundDomains]="true" [gradient]="true" [xAxis]="true" [yAxis]="true">
        </ngx-charts-line-chart>
    </div>
</div>
```

```scss
:host {
    height: 100%;
    width: 100%;
}

.chart-container {
    padding-left: 10px;
    padding-right: 10px;
}

.spectre-line-chart {
    height: 100%;
    width: 100%;
    float: left;
}
```

Edit the `.chart-container` class in order to change the chart positioning.

Cheers!
