### ISSUE TITLE
Stroke and fill should use currentColor.

### ISSUE THREAD

**Issue by y0nd0** [swimlane/ngx-charts#1574]
`stroke` and `fill ` should use `currentColor`. 

```scss
this-lib {
  stroke: currentColor;
  fill: currentColor;
}
```

At this moment the svg text is fixed black. The css `color` property does not work with svg. So you have also set `stroke` and / or `fill`.
When this is fixed, you can use the chart in every website theme. (incl. dark mode). Without any further changes / hacks. 

Cheers.
