### ISSUE TITLE
Can't change text color on labels

### ISSUE THREAD

**Issue by westlakem** [swimlane/ngx-charts#1587]
Self explanatory...

Tried setting "color" css on the element and nothing.  Makes it real hard to see on a dark-themed background

**Comment by Levon770** [comment]
use fill instead

`.pie-label {
    font-size: 11px;
    fill: red;
}`

**Comment by Rob4226** [comment]
Just to add what worked for me when trying to style from the component scss file:
```scss
::ng-deep .ngx-charts { text { fill: #fff !important; } }
```
Thanks to who posted this in another issue: https://github.com/swimlane/ngx-charts/issues/740#issuecomment-368643090

**Comment by linflux** [comment]
I have the same issue today and after a lot of research the only style that works for me was:
```css
 .ngx-charts, text { fill: #fff; }
```
Using ngx-charts version 19.2.
