### ISSUE TITLE
Demo Timeline in Light Theme doesn t display the graph

### ISSUE THREAD

**Issue by ranouf** [swimlane/ngx-charts#631]
Hi,

I noticed that the Chart is not correctly display on Firefox in light Mode for TimeLine Demo Theme:
https://swimlane.github.io/ngx-charts/#/ngx-charts/timeline-filter-bar-chart-demo

**Comment by pigant** [comment]
![imagen](https://user-images.githubusercontent.com/14183160/33559947-228cd0c6-d8ed-11e7-9d5c-64b2e852635b.png)

**Comment by lewiswashere** [comment]
![Capturechart](https://user-images.githubusercontent.com/19499302/59483623-d33d5880-8e33-11e9-876a-41406ae4c1a3.PNG)
@ranouf looks like this is still an issue in both Firefox & Chrome while using light theme. After copying over the template [timeline-filter-bar-chart](https://github.com/swimlane/ngx-charts/tree/master/demo/timeline-filter-bar-chart) .ts & .scss into my project, I added `opacity: 0.1;` to the `.brush-background` class as a temporary workaround: 
```scss
.timeline-filter-bar-chart {
  .timeline {
    .brush-background {
      fill: rgba(0,0,0,0.05);
      /* Added this... */
      opacity: 0.1;
    }
 }
```
